apiVersion: v1
kind: Service
metadata:
  name: webserver-service-events
  namespace: infra
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
