pipeline:
  identifier: Build_Pacco79_testing_1739274315786
  name: Build testing
  orgIdentifier: default
  projectIdentifier: events
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Pacco79/testing
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
